// AutolinkedNativeModules.g.cs contents generated by "react-native autolink-windows"

using System.Collections.Generic;

// Namespaces from react-native-camera
using ReactNativeCameraCPP;

// Namespaces from react-native-device-info
using RNDeviceInfoCPP;

// Namespaces from react-native-file-picker
using ReactNativeFilePicker;

// Namespaces from react-native-view-shot
using RNViewShot;

// Namespaces from react-native-webview
using ReactNativeWebView;

// Namespaces from react-native-windows-msal
using RNWMsal;

// Namespaces from rn-fetch-blob
using RNFetchBlob;

namespace Microsoft.ReactNative.Managed
{
    internal static class AutolinkedNativeModules
    {
        internal static void RegisterAutolinkedNativeModulePackages(IList<IReactPackageProvider> packageProviders)
        { 
            // IReactPackageProviders from react-native-camera
            packageProviders.Add(new ReactNativeCameraCPP.ReactPackageProvider());
            // IReactPackageProviders from react-native-device-info
            packageProviders.Add(new RNDeviceInfoCPP.ReactPackageProvider());
            // IReactPackageProviders from react-native-file-picker
            packageProviders.Add(new ReactNativeFilePicker.ReactPackageProvider());
            // IReactPackageProviders from react-native-view-shot
            packageProviders.Add(new RNViewShot.ReactPackageProvider());
            // IReactPackageProviders from react-native-webview
            packageProviders.Add(new ReactNativeWebView.ReactPackageProvider());
            // IReactPackageProviders from react-native-windows-msal
            packageProviders.Add(new RNWMsal.ReactPackageProvider());
            // IReactPackageProviders from rn-fetch-blob
            packageProviders.Add(new RNFetchBlob.ReactPackageProvider());
        }
    }
}
